# FindCotire.cmake 1.7.6 generated file
# /home/ubuntu/ezipsoft/src/tfs_CXX_FindCotire.cmake
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_EXTENSIONS "inc;inl;ipp")
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_PATH "")
set (COTIRE_CLEAN_ALL_TARGET_NAME "clean_cotire")
set (COTIRE_CLEAN_TARGET_SUFFIX "_clean_cotire")
set (COTIRE_CMAKE_MODULE_FILE "/home/ubuntu/ezipsoft/cmake/FindCotire.cmake")
set (COTIRE_CMAKE_MODULE_VERSION "1.7.6")
set (COTIRE_DEBUG "OFF")
set (COTIRE_INTDIR "cotire")
set (COTIRE_MAXIMUM_NUMBER_OF_UNITY_INCLUDES "0")
set (COTIRE_MINIMUM_NUMBER_OF_TARGET_SOURCES "3")
set (COTIRE_PCH_ALL_TARGET_NAME "all_pch")
set (COTIRE_PCH_TARGET_SUFFIX "_pch")
set (COTIRE_PREFIX_HEADER_FILENAME_SUFFIX "_prefix")
set (COTIRE_TARGETS_FOLDER "cotire")
set (COTIRE_TARGET_COMPILE_FLAGS_RELEASE "-Wall;-Werror;-Wall;-Werror;-pipe;-fvisibility=hidden;-march=native;-O2;-fno-strict-aliasing;-flto;-std=c++11")
set (COTIRE_TARGET_CONFIGURATION_TYPES "Release")
set (COTIRE_TARGET_IGNORE_PATH "/home/ubuntu/ezipsoft")
set (COTIRE_TARGET_INCLUDE_DIRECTORIES_RELEASE "/usr/include/mysql;/usr/include/luajit-2.1")
set (COTIRE_TARGET_INCLUDE_PRIORITY_PATH "")
set (COTIRE_TARGET_LANGUAGE "CXX")
set (COTIRE_TARGET_MAXIMUM_NUMBER_OF_INCLUDES "")
set (COTIRE_TARGET_POST_UNDEFS "")
set (COTIRE_TARGET_PRE_UNDEFS "")
set (COTIRE_TARGET_SOURCES "/home/ubuntu/ezipsoft/src/otpch.cpp;/home/ubuntu/ezipsoft/src/account.cpp;/home/ubuntu/ezipsoft/src/actions.cpp;/home/ubuntu/ezipsoft/src/ban.cpp;/home/ubuntu/ezipsoft/src/baseevents.cpp;/home/ubuntu/ezipsoft/src/bed.cpp;/home/ubuntu/ezipsoft/src/chat.cpp;/home/ubuntu/ezipsoft/src/combat.cpp;/home/ubuntu/ezipsoft/src/condition.cpp;/home/ubuntu/ezipsoft/src/configmanager.cpp;/home/ubuntu/ezipsoft/src/connection.cpp;/home/ubuntu/ezipsoft/src/container.cpp;/home/ubuntu/ezipsoft/src/creature.cpp;/home/ubuntu/ezipsoft/src/creatureevent.cpp;/home/ubuntu/ezipsoft/src/cylinder.cpp;/home/ubuntu/ezipsoft/src/database.cpp;/home/ubuntu/ezipsoft/src/databasemanager.cpp;/home/ubuntu/ezipsoft/src/databasetasks.cpp;/home/ubuntu/ezipsoft/src/depotchest.cpp;/home/ubuntu/ezipsoft/src/depotlocker.cpp;/home/ubuntu/ezipsoft/src/events.cpp;/home/ubuntu/ezipsoft/src/fileloader.cpp;/home/ubuntu/ezipsoft/src/game.cpp;/home/ubuntu/ezipsoft/src/gamestore.cpp;/home/ubuntu/ezipsoft/src/globalevent.cpp;/home/ubuntu/ezipsoft/src/guild.cpp;/home/ubuntu/ezipsoft/src/groups.cpp;/home/ubuntu/ezipsoft/src/house.cpp;/home/ubuntu/ezipsoft/src/inbox.cpp;/home/ubuntu/ezipsoft/src/ioguild.cpp;/home/ubuntu/ezipsoft/src/iologindata.cpp;/home/ubuntu/ezipsoft/src/iomap.cpp;/home/ubuntu/ezipsoft/src/iomapserialize.cpp;/home/ubuntu/ezipsoft/src/iomarket.cpp;/home/ubuntu/ezipsoft/src/item.cpp;/home/ubuntu/ezipsoft/src/items.cpp;/home/ubuntu/ezipsoft/src/imbuements.cpp;/home/ubuntu/ezipsoft/src/luascript.cpp;/home/ubuntu/ezipsoft/src/mailbox.cpp;/home/ubuntu/ezipsoft/src/map.cpp;/home/ubuntu/ezipsoft/src/modules.cpp;/home/ubuntu/ezipsoft/src/monster.cpp;/home/ubuntu/ezipsoft/src/monsters.cpp;/home/ubuntu/ezipsoft/src/mounts.cpp;/home/ubuntu/ezipsoft/src/movement.cpp;/home/ubuntu/ezipsoft/src/networkmessage.cpp;/home/ubuntu/ezipsoft/src/npc.cpp;/home/ubuntu/ezipsoft/src/otserv.cpp;/home/ubuntu/ezipsoft/src/outfit.cpp;/home/ubuntu/ezipsoft/src/outputmessage.cpp;/home/ubuntu/ezipsoft/src/party.cpp;/home/ubuntu/ezipsoft/src/player.cpp;/home/ubuntu/ezipsoft/src/prey.cpp;/home/ubuntu/ezipsoft/src/position.cpp;/home/ubuntu/ezipsoft/src/protocol.cpp;/home/ubuntu/ezipsoft/src/protocolgame.cpp;/home/ubuntu/ezipsoft/src/protocollogin.cpp;/home/ubuntu/ezipsoft/src/protocolold.cpp;/home/ubuntu/ezipsoft/src/protocolstatus.cpp;/home/ubuntu/ezipsoft/src/raids.cpp;/home/ubuntu/ezipsoft/src/reward.cpp;/home/ubuntu/ezipsoft/src/rewardchest.cpp;/home/ubuntu/ezipsoft/src/rsa.cpp;/home/ubuntu/ezipsoft/src/scheduler.cpp;/home/ubuntu/ezipsoft/src/scriptmanager.cpp;/home/ubuntu/ezipsoft/src/script.cpp;/home/ubuntu/ezipsoft/src/server.cpp;/home/ubuntu/ezipsoft/src/signals.cpp;/home/ubuntu/ezipsoft/src/spawn.cpp;/home/ubuntu/ezipsoft/src/spells.cpp;/home/ubuntu/ezipsoft/src/talkaction.cpp;/home/ubuntu/ezipsoft/src/tasks.cpp;/home/ubuntu/ezipsoft/src/teleport.cpp;/home/ubuntu/ezipsoft/src/thing.cpp;/home/ubuntu/ezipsoft/src/tile.cpp;/home/ubuntu/ezipsoft/src/tools.cpp;/home/ubuntu/ezipsoft/src/trashholder.cpp;/home/ubuntu/ezipsoft/src/vocation.cpp;/home/ubuntu/ezipsoft/src/waitlist.cpp;/home/ubuntu/ezipsoft/src/weapons.cpp;/home/ubuntu/ezipsoft/src/wildcardtree.cpp;/home/ubuntu/ezipsoft/src/xtea.cpp")
set (COTIRE_UNITY_BUILD_ALL_TARGET_NAME "all_unity")
set (COTIRE_UNITY_BUILD_TARGET_SUFFIX "_unity")
set (COTIRE_UNITY_OUTPUT_DIRECTORY "")
set (COTIRE_UNITY_SOURCE_EXCLUDE_EXTENSIONS "m;mm")
set (COTIRE_UNITY_SOURCE_FILENAME_SUFFIX "_unity")
set (CMAKE_GENERATOR "Unix Makefiles")
set (CMAKE_BUILD_TYPE "Release")
set (CMAKE_CXX_COMPILER_ID "GNU")
set (CMAKE_CXX_COMPILER_VERSION "7.5.0")
set (CMAKE_CXX_COMPILER "/usr/bin/c++")
set (CMAKE_CXX_COMPILER_ARG1 "")
set (CMAKE_INCLUDE_FLAG_CXX "-I")
set (CMAKE_INCLUDE_SYSTEM_FLAG_CXX "-isystem ")
set (CMAKE_CXX_SOURCE_FILE_EXTENSIONS "C;M;c++;cc;cpp;cxx;mm;CPP")
